export const KATA_LIST: { number: number; name: string }[] = [
  { number: 1,  name: "Anan" },
  { number: 2,  name: "Anan Dai" },
  { number: 3,  name: "Annan" },
  { number: 4,  name: "Annanko" },
  { number: 5,  name: "Bassai Dai" },
  { number: 6,  name: "Bassai Sho" },
  { number: 7,  name: "Chatan Yara No Kushanku" },
  { number: 8,  name: "Chatanyara No Sai" },
  { number: 9,  name: "Chinte" },
  { number: 10, name: "Chito" },
  { number: 11, name: "Empi" },
  { number: 12, name: "Enpi" },
  { number: 13, name: "Garyu" },
  { number: 14, name: "Gankaku" },
  { number: 15, name: "Gankaku Sho" },
  { number: 16, name: "Gekisai Dai Ichi" },
  { number: 17, name: "Gekisai Dai Ni" },
  { number: 18, name: "Gojushiho Dai" },
  { number: 19, name: "Gojushiho Sho" },
  { number: 20, name: "Hakucho" },
  { number: 21, name: "Hakutsuru" },
  { number: 22, name: "Hangetsu" },
  { number: 23, name: "Heian Godan" },
  { number: 24, name: "Heian Jodan" },
  { number: 25, name: "Heian Nidan" },
  { number: 26, name: "Heian Sandan" },
  { number: 27, name: "Heian Shodan" },
  { number: 28, name: "Heian Yondan" },
  { number: 29, name: "Hyakuhachiho" },
  { number: 30, name: "Ji'in" },
  { number: 31, name: "Jion" },
  { number: 32, name: "Jitte" },
  { number: 33, name: "Juroku" },
  { number: 34, name: "Kakuho" },
  { number: 35, name: "Kakuyoku Nidan" },
  { number: 36, name: "Kakuyoku Sandan" },
  { number: 37, name: "Kakuyoku Shodan" },
  { number: 38, name: "Kanku Dai" },
  { number: 39, name: "Kanku Sho" },
  { number: 40, name: "Kanshu" },
  { number: 41, name: "Kibaken" },
  { number: 42, name: "Kihon Kata" },
  { number: 43, name: "Kihon Kata Ichi" },
  { number: 44, name: "Kihon Kata Ni" },
  { number: 45, name: "Kihon Kata San" },
  { number: 46, name: "Kihon No Kata" },
  { number: 47, name: "Kissaki Kai" },
  { number: 48, name: "Ko Soku Dai" },
  { number: 49, name: "Ko Soku Sho" },
  { number: 50, name: "Kohaku" },
  { number: 51, name: "Koshiki Naifanchi" },
  { number: 52, name: "Kukan Sho" },
  { number: 53, name: "Kushanku" },
  { number: 54, name: "Kushanku Sho" },
  { number: 55, name: "Matsukaze" },
  { number: 56, name: "Matsumura No Bassai" },
  { number: 57, name: "Matsumura No Rohai" },
  { number: 58, name: "Meikyo" },
  { number: 59, name: "Meikyo Nidan" },
  { number: 60, name: "Meikyo Sandan" },
  { number: 61, name: "Miyojo" },
  { number: 62, name: "Naifanchi Nidan" },
  { number: 63, name: "Naifanchi Sandan" },
  { number: 64, name: "Naifanchi Shodan" },
  { number: 65, name: "Naihanchi" },
  { number: 66, name: "Nijushiho" },
  { number: 67, name: "Nipaipo" },
  { number: 68, name: "Ohan" },
  { number: 69, name: "Ohan Dai" },
  { number: 70, name: "Okinawa No Kata" },
  { number: 71, name: "Pachu" },
  { number: 72, name: "Paiku" },
  { number: 73, name: "Papuren" },
  { number: 74, name: "Passai Dai" },
  { number: 75, name: "Passai Sho" },
  { number: 76, name: "Pinan Godan" },
  { number: 77, name: "Pinan Nidan" },
  { number: 78, name: "Pinan Sandan" },
  { number: 79, name: "Pinan Shodan" },
  { number: 80, name: "Pinan Yondan" },
  { number: 81, name: "Roppo" },
  { number: 82, name: "Rohai" },
  { number: 83, name: "Saifa" },
  { number: 84, name: "Sanchin" },
  { number: 85, name: "Sanseiru" },
  { number: 86, name: "Seipai" },
  { number: 87, name: "Seienchin" },
  { number: 88, name: "Seisan" },
  { number: 89, name: "Shisochin" },
  { number: 90, name: "Shorin No Kata" },
  { number: 91, name: "Sochin" },
  { number: 92, name: "Suparinpei" },
  { number: 93, name: "Taikyoku Shodan" },
  { number: 94, name: "Taikyoku Nidan" },
  { number: 95, name: "Taikyoku Sandan" },
  { number: 96, name: "Tensho" },
  { number: 97, name: "Tomari No Bassai" },
  { number: 98, name: "Unsu" },
  { number: 99, name: "Uroken" },
  { number: 100, name: "Useishi" },
  { number: 101, name: "Wankan" },
  { number: 102, name: "Wanshu" },
];

/** Returns the kata numbers permitted for the full WKF list (all 102). */
export const WKF_ALLOWED_KATA_NUMBERS: number[] = KATA_LIST.map(k => k.number);

/** WKF Appendix 2 — 14 official competition categories */
export const WKF_KATA_CATEGORIES: string[] = [
  "Male Kata Individual",
  "Female Kata Individual",
  "Male Kata Team",
  "Female Kata Team",
  "Junior Male Kata Individual",
  "Junior Female Kata Individual",
  "Cadet Male Kata Individual",
  "Cadet Female Kata Individual",
  "Youth Male Kata Individual",
  "Youth Female Kata Individual",
  "Para-Karate Male Kata",
  "Para-Karate Female Kata",
  "Veteran Male Kata",
  "Veteran Female Kata",
];

export type KataEntry = { number: number; name: string };
